package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1



/**
 * Candidato generated by hbm2java
 */
public class Candidato  implements java.io.Serializable {


     private long nuInscricao;
     private Escola escola;
     private Municipio municipioByCodMunicipioNascimento;
     private Municipio municipioByCodMunicipioProva;
     private Municipio municipioByCodMunicipioResidencia;
     private Uf ufByCodUfNascimento;
     private Uf ufByCodUfResidencia;
     private Uf ufByCodUfProva;
     private Short nuAno;
     private Boolean inEstudaClasseHospitalar;
     private Byte idade;
     private String tpSexo;
     private Boolean nacionalidade;
     private Boolean stConclusao;
     private Short anoConcluiu;
     private Boolean tpEscola;
     private Boolean inTpEnsino;
     private Boolean tpEstadoCivil;
     private Boolean tpCorRaca;
     private Boolean inBaixaVisao;
     private Boolean inCegueira;
     private Boolean inSurdez;
     private Boolean inDeficienciaAuditiva;
     private Boolean inSurdoCegueira;
     private Boolean inDeficienciaFisica;
     private Boolean inDeficienciaMental;
     private Boolean inDeficitAtencao;
     private Boolean inDislexia;
     private Boolean inGestante;
     private Boolean inLactante;
     private Boolean inIdoso;
     private Boolean inAutismo;
     private Boolean inSabatista;
     private Boolean inBraille;
     private Boolean inAmpliada24;
     private Boolean inAmpliada18;
     private Boolean inLedor;
     private Boolean inTranscricao;
     private Boolean inLibras;
     private Boolean inLeituraLabial;
     private Boolean inMesaCadeiraRodas;
     private Boolean inMesaCadeiraSeparada;
     private Boolean inApoioPerna;
     private Boolean inGuiaInterprete;
     private Socioeconomico socioeconomico;
     private Notas notas;

    public Candidato() {
    }

	
    public Candidato(long nuInscricao) {
        this.nuInscricao = nuInscricao;
    }
    public Candidato(long nuInscricao, Escola escola, Municipio municipioByCodMunicipioNascimento, Municipio municipioByCodMunicipioProva, Municipio municipioByCodMunicipioResidencia, Uf ufByCodUfNascimento, Uf ufByCodUfResidencia, Uf ufByCodUfProva, Short nuAno, Boolean inEstudaClasseHospitalar, Byte idade, String tpSexo, Boolean nacionalidade, Boolean stConclusao, Short anoConcluiu, Boolean tpEscola, Boolean inTpEnsino, Boolean tpEstadoCivil, Boolean tpCorRaca, Boolean inBaixaVisao, Boolean inCegueira, Boolean inSurdez, Boolean inDeficienciaAuditiva, Boolean inSurdoCegueira, Boolean inDeficienciaFisica, Boolean inDeficienciaMental, Boolean inDeficitAtencao, Boolean inDislexia, Boolean inGestante, Boolean inLactante, Boolean inIdoso, Boolean inAutismo, Boolean inSabatista, Boolean inBraille, Boolean inAmpliada24, Boolean inAmpliada18, Boolean inLedor, Boolean inTranscricao, Boolean inLibras, Boolean inLeituraLabial, Boolean inMesaCadeiraRodas, Boolean inMesaCadeiraSeparada, Boolean inApoioPerna, Boolean inGuiaInterprete, Socioeconomico socioeconomico, Notas notas) {
       this.nuInscricao = nuInscricao;
       this.escola = escola;
       this.municipioByCodMunicipioNascimento = municipioByCodMunicipioNascimento;
       this.municipioByCodMunicipioProva = municipioByCodMunicipioProva;
       this.municipioByCodMunicipioResidencia = municipioByCodMunicipioResidencia;
       this.ufByCodUfNascimento = ufByCodUfNascimento;
       this.ufByCodUfResidencia = ufByCodUfResidencia;
       this.ufByCodUfProva = ufByCodUfProva;
       this.nuAno = nuAno;
       this.inEstudaClasseHospitalar = inEstudaClasseHospitalar;
       this.idade = idade;
       this.tpSexo = tpSexo;
       this.nacionalidade = nacionalidade;
       this.stConclusao = stConclusao;
       this.anoConcluiu = anoConcluiu;
       this.tpEscola = tpEscola;
       this.inTpEnsino = inTpEnsino;
       this.tpEstadoCivil = tpEstadoCivil;
       this.tpCorRaca = tpCorRaca;
       this.inBaixaVisao = inBaixaVisao;
       this.inCegueira = inCegueira;
       this.inSurdez = inSurdez;
       this.inDeficienciaAuditiva = inDeficienciaAuditiva;
       this.inSurdoCegueira = inSurdoCegueira;
       this.inDeficienciaFisica = inDeficienciaFisica;
       this.inDeficienciaMental = inDeficienciaMental;
       this.inDeficitAtencao = inDeficitAtencao;
       this.inDislexia = inDislexia;
       this.inGestante = inGestante;
       this.inLactante = inLactante;
       this.inIdoso = inIdoso;
       this.inAutismo = inAutismo;
       this.inSabatista = inSabatista;
       this.inBraille = inBraille;
       this.inAmpliada24 = inAmpliada24;
       this.inAmpliada18 = inAmpliada18;
       this.inLedor = inLedor;
       this.inTranscricao = inTranscricao;
       this.inLibras = inLibras;
       this.inLeituraLabial = inLeituraLabial;
       this.inMesaCadeiraRodas = inMesaCadeiraRodas;
       this.inMesaCadeiraSeparada = inMesaCadeiraSeparada;
       this.inApoioPerna = inApoioPerna;
       this.inGuiaInterprete = inGuiaInterprete;
       this.socioeconomico = socioeconomico;
       this.notas = notas;
    }
   
    public long getNuInscricao() {
        return this.nuInscricao;
    }
    
    public void setNuInscricao(long nuInscricao) {
        this.nuInscricao = nuInscricao;
    }
    public Escola getEscola() {
        return this.escola;
    }
    
    public void setEscola(Escola escola) {
        this.escola = escola;
    }
    public Municipio getMunicipioByCodMunicipioNascimento() {
        return this.municipioByCodMunicipioNascimento;
    }
    
    public void setMunicipioByCodMunicipioNascimento(Municipio municipioByCodMunicipioNascimento) {
        this.municipioByCodMunicipioNascimento = municipioByCodMunicipioNascimento;
    }
    public Municipio getMunicipioByCodMunicipioProva() {
        return this.municipioByCodMunicipioProva;
    }
    
    public void setMunicipioByCodMunicipioProva(Municipio municipioByCodMunicipioProva) {
        this.municipioByCodMunicipioProva = municipioByCodMunicipioProva;
    }
    public Municipio getMunicipioByCodMunicipioResidencia() {
        return this.municipioByCodMunicipioResidencia;
    }
    
    public void setMunicipioByCodMunicipioResidencia(Municipio municipioByCodMunicipioResidencia) {
        this.municipioByCodMunicipioResidencia = municipioByCodMunicipioResidencia;
    }
    public Uf getUfByCodUfNascimento() {
        return this.ufByCodUfNascimento;
    }
    
    public void setUfByCodUfNascimento(Uf ufByCodUfNascimento) {
        this.ufByCodUfNascimento = ufByCodUfNascimento;
    }
    public Uf getUfByCodUfResidencia() {
        return this.ufByCodUfResidencia;
    }
    
    public void setUfByCodUfResidencia(Uf ufByCodUfResidencia) {
        this.ufByCodUfResidencia = ufByCodUfResidencia;
    }
    public Uf getUfByCodUfProva() {
        return this.ufByCodUfProva;
    }
    
    public void setUfByCodUfProva(Uf ufByCodUfProva) {
        this.ufByCodUfProva = ufByCodUfProva;
    }
    public Short getNuAno() {
        return this.nuAno;
    }
    
    public void setNuAno(Short nuAno) {
        this.nuAno = nuAno;
    }
    public Boolean getInEstudaClasseHospitalar() {
        return this.inEstudaClasseHospitalar;
    }
    
    public void setInEstudaClasseHospitalar(Boolean inEstudaClasseHospitalar) {
        this.inEstudaClasseHospitalar = inEstudaClasseHospitalar;
    }
    public Byte getIdade() {
        return this.idade;
    }
    
    public void setIdade(Byte idade) {
        this.idade = idade;
    }
    public String getTpSexo() {
        return this.tpSexo;
    }
    
    public void setTpSexo(String tpSexo) {
        this.tpSexo = tpSexo;
    }
    public Boolean getNacionalidade() {
        return this.nacionalidade;
    }
    
    public void setNacionalidade(Boolean nacionalidade) {
        this.nacionalidade = nacionalidade;
    }
    public Boolean getStConclusao() {
        return this.stConclusao;
    }
    
    public void setStConclusao(Boolean stConclusao) {
        this.stConclusao = stConclusao;
    }
    public Short getAnoConcluiu() {
        return this.anoConcluiu;
    }
    
    public void setAnoConcluiu(Short anoConcluiu) {
        this.anoConcluiu = anoConcluiu;
    }
    public Boolean getTpEscola() {
        return this.tpEscola;
    }
    
    public void setTpEscola(Boolean tpEscola) {
        this.tpEscola = tpEscola;
    }
    public Boolean getInTpEnsino() {
        return this.inTpEnsino;
    }
    
    public void setInTpEnsino(Boolean inTpEnsino) {
        this.inTpEnsino = inTpEnsino;
    }
    public Boolean getTpEstadoCivil() {
        return this.tpEstadoCivil;
    }
    
    public void setTpEstadoCivil(Boolean tpEstadoCivil) {
        this.tpEstadoCivil = tpEstadoCivil;
    }
    public Boolean getTpCorRaca() {
        return this.tpCorRaca;
    }
    
    public void setTpCorRaca(Boolean tpCorRaca) {
        this.tpCorRaca = tpCorRaca;
    }
    public Boolean getInBaixaVisao() {
        return this.inBaixaVisao;
    }
    
    public void setInBaixaVisao(Boolean inBaixaVisao) {
        this.inBaixaVisao = inBaixaVisao;
    }
    public Boolean getInCegueira() {
        return this.inCegueira;
    }
    
    public void setInCegueira(Boolean inCegueira) {
        this.inCegueira = inCegueira;
    }
    public Boolean getInSurdez() {
        return this.inSurdez;
    }
    
    public void setInSurdez(Boolean inSurdez) {
        this.inSurdez = inSurdez;
    }
    public Boolean getInDeficienciaAuditiva() {
        return this.inDeficienciaAuditiva;
    }
    
    public void setInDeficienciaAuditiva(Boolean inDeficienciaAuditiva) {
        this.inDeficienciaAuditiva = inDeficienciaAuditiva;
    }
    public Boolean getInSurdoCegueira() {
        return this.inSurdoCegueira;
    }
    
    public void setInSurdoCegueira(Boolean inSurdoCegueira) {
        this.inSurdoCegueira = inSurdoCegueira;
    }
    public Boolean getInDeficienciaFisica() {
        return this.inDeficienciaFisica;
    }
    
    public void setInDeficienciaFisica(Boolean inDeficienciaFisica) {
        this.inDeficienciaFisica = inDeficienciaFisica;
    }
    public Boolean getInDeficienciaMental() {
        return this.inDeficienciaMental;
    }
    
    public void setInDeficienciaMental(Boolean inDeficienciaMental) {
        this.inDeficienciaMental = inDeficienciaMental;
    }
    public Boolean getInDeficitAtencao() {
        return this.inDeficitAtencao;
    }
    
    public void setInDeficitAtencao(Boolean inDeficitAtencao) {
        this.inDeficitAtencao = inDeficitAtencao;
    }
    public Boolean getInDislexia() {
        return this.inDislexia;
    }
    
    public void setInDislexia(Boolean inDislexia) {
        this.inDislexia = inDislexia;
    }
    public Boolean getInGestante() {
        return this.inGestante;
    }
    
    public void setInGestante(Boolean inGestante) {
        this.inGestante = inGestante;
    }
    public Boolean getInLactante() {
        return this.inLactante;
    }
    
    public void setInLactante(Boolean inLactante) {
        this.inLactante = inLactante;
    }
    public Boolean getInIdoso() {
        return this.inIdoso;
    }
    
    public void setInIdoso(Boolean inIdoso) {
        this.inIdoso = inIdoso;
    }
    public Boolean getInAutismo() {
        return this.inAutismo;
    }
    
    public void setInAutismo(Boolean inAutismo) {
        this.inAutismo = inAutismo;
    }
    public Boolean getInSabatista() {
        return this.inSabatista;
    }
    
    public void setInSabatista(Boolean inSabatista) {
        this.inSabatista = inSabatista;
    }
    public Boolean getInBraille() {
        return this.inBraille;
    }
    
    public void setInBraille(Boolean inBraille) {
        this.inBraille = inBraille;
    }
    public Boolean getInAmpliada24() {
        return this.inAmpliada24;
    }
    
    public void setInAmpliada24(Boolean inAmpliada24) {
        this.inAmpliada24 = inAmpliada24;
    }
    public Boolean getInAmpliada18() {
        return this.inAmpliada18;
    }
    
    public void setInAmpliada18(Boolean inAmpliada18) {
        this.inAmpliada18 = inAmpliada18;
    }
    public Boolean getInLedor() {
        return this.inLedor;
    }
    
    public void setInLedor(Boolean inLedor) {
        this.inLedor = inLedor;
    }
    public Boolean getInTranscricao() {
        return this.inTranscricao;
    }
    
    public void setInTranscricao(Boolean inTranscricao) {
        this.inTranscricao = inTranscricao;
    }
    public Boolean getInLibras() {
        return this.inLibras;
    }
    
    public void setInLibras(Boolean inLibras) {
        this.inLibras = inLibras;
    }
    public Boolean getInLeituraLabial() {
        return this.inLeituraLabial;
    }
    
    public void setInLeituraLabial(Boolean inLeituraLabial) {
        this.inLeituraLabial = inLeituraLabial;
    }
    public Boolean getInMesaCadeiraRodas() {
        return this.inMesaCadeiraRodas;
    }
    
    public void setInMesaCadeiraRodas(Boolean inMesaCadeiraRodas) {
        this.inMesaCadeiraRodas = inMesaCadeiraRodas;
    }
    public Boolean getInMesaCadeiraSeparada() {
        return this.inMesaCadeiraSeparada;
    }
    
    public void setInMesaCadeiraSeparada(Boolean inMesaCadeiraSeparada) {
        this.inMesaCadeiraSeparada = inMesaCadeiraSeparada;
    }
    public Boolean getInApoioPerna() {
        return this.inApoioPerna;
    }
    
    public void setInApoioPerna(Boolean inApoioPerna) {
        this.inApoioPerna = inApoioPerna;
    }
    public Boolean getInGuiaInterprete() {
        return this.inGuiaInterprete;
    }
    
    public void setInGuiaInterprete(Boolean inGuiaInterprete) {
        this.inGuiaInterprete = inGuiaInterprete;
    }
    public Socioeconomico getSocioeconomico() {
        return this.socioeconomico;
    }
    
    public void setSocioeconomico(Socioeconomico socioeconomico) {
        this.socioeconomico = socioeconomico;
    }
    public Notas getNotas() {
        return this.notas;
    }
    
    public void setNotas(Notas notas) {
        this.notas = notas;
    }




}


