package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escola generated by hbm2java
 */
public class Escola  implements java.io.Serializable {


     private int codEscola;
     private Municipio municipio;
     private Uf uf;
     private Boolean idDependenciaAdmEsc;
     private Boolean idLocalizacaoEsc;
     private Boolean sitFuncEsc;
     private Set candidatos = new HashSet(0);

    public Escola() {
    }

	
    public Escola(int codEscola) {
        this.codEscola = codEscola;
    }
    public Escola(int codEscola, Municipio municipio, Uf uf, Boolean idDependenciaAdmEsc, Boolean idLocalizacaoEsc, Boolean sitFuncEsc, Set candidatos) {
       this.codEscola = codEscola;
       this.municipio = municipio;
       this.uf = uf;
       this.idDependenciaAdmEsc = idDependenciaAdmEsc;
       this.idLocalizacaoEsc = idLocalizacaoEsc;
       this.sitFuncEsc = sitFuncEsc;
       this.candidatos = candidatos;
    }
   
    public int getCodEscola() {
        return this.codEscola;
    }
    
    public void setCodEscola(int codEscola) {
        this.codEscola = codEscola;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Uf getUf() {
        return this.uf;
    }
    
    public void setUf(Uf uf) {
        this.uf = uf;
    }
    public Boolean getIdDependenciaAdmEsc() {
        return this.idDependenciaAdmEsc;
    }
    
    public void setIdDependenciaAdmEsc(Boolean idDependenciaAdmEsc) {
        this.idDependenciaAdmEsc = idDependenciaAdmEsc;
    }
    public Boolean getIdLocalizacaoEsc() {
        return this.idLocalizacaoEsc;
    }
    
    public void setIdLocalizacaoEsc(Boolean idLocalizacaoEsc) {
        this.idLocalizacaoEsc = idLocalizacaoEsc;
    }
    public Boolean getSitFuncEsc() {
        return this.sitFuncEsc;
    }
    
    public void setSitFuncEsc(Boolean sitFuncEsc) {
        this.sitFuncEsc = sitFuncEsc;
    }
    public Set getCandidatos() {
        return this.candidatos;
    }
    
    public void setCandidatos(Set candidatos) {
        this.candidatos = candidatos;
    }




}


