package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private int codMunicipio;
     private String noMunicipio;
     private Set candidatosForCodMunicipioNascimento = new HashSet(0);
     private Set candidatosForCodMunicipioProva = new HashSet(0);
     private Set candidatosForCodMunicipioResidencia = new HashSet(0);
     private Set escolas = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(int codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public Municipio(int codMunicipio, String noMunicipio, Set candidatosForCodMunicipioNascimento, Set candidatosForCodMunicipioProva, Set candidatosForCodMunicipioResidencia, Set escolas) {
       this.codMunicipio = codMunicipio;
       this.noMunicipio = noMunicipio;
       this.candidatosForCodMunicipioNascimento = candidatosForCodMunicipioNascimento;
       this.candidatosForCodMunicipioProva = candidatosForCodMunicipioProva;
       this.candidatosForCodMunicipioResidencia = candidatosForCodMunicipioResidencia;
       this.escolas = escolas;
    }
   
    public int getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(int codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public String getNoMunicipio() {
        return this.noMunicipio;
    }
    
    public void setNoMunicipio(String noMunicipio) {
        this.noMunicipio = noMunicipio;
    }
    public Set getCandidatosForCodMunicipioNascimento() {
        return this.candidatosForCodMunicipioNascimento;
    }
    
    public void setCandidatosForCodMunicipioNascimento(Set candidatosForCodMunicipioNascimento) {
        this.candidatosForCodMunicipioNascimento = candidatosForCodMunicipioNascimento;
    }
    public Set getCandidatosForCodMunicipioProva() {
        return this.candidatosForCodMunicipioProva;
    }
    
    public void setCandidatosForCodMunicipioProva(Set candidatosForCodMunicipioProva) {
        this.candidatosForCodMunicipioProva = candidatosForCodMunicipioProva;
    }
    public Set getCandidatosForCodMunicipioResidencia() {
        return this.candidatosForCodMunicipioResidencia;
    }
    
    public void setCandidatosForCodMunicipioResidencia(Set candidatosForCodMunicipioResidencia) {
        this.candidatosForCodMunicipioResidencia = candidatosForCodMunicipioResidencia;
    }
    public Set getEscolas() {
        return this.escolas;
    }
    
    public void setEscolas(Set escolas) {
        this.escolas = escolas;
    }




}


