package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1



/**
 * Notas generated by hbm2java
 */
public class Notas  implements java.io.Serializable {


     private long nuInscricao;
     private Candidato candidato;
     private Double notaCn;
     private Double notaCh;
     private Double notaLc;
     private Double notaMt;
     private Double nuNotaRedacao;

    public Notas() {
    }

	
    public Notas(Candidato candidato) {
        this.candidato = candidato;
    }
    public Notas(Candidato candidato, Double notaCn, Double notaCh, Double notaLc, Double notaMt, Double nuNotaRedacao) {
       this.candidato = candidato;
       this.notaCn = notaCn;
       this.notaCh = notaCh;
       this.notaLc = notaLc;
       this.notaMt = notaMt;
       this.nuNotaRedacao = nuNotaRedacao;
    }
   
    public long getNuInscricao() {
        return this.nuInscricao;
    }
    
    public void setNuInscricao(long nuInscricao) {
        this.nuInscricao = nuInscricao;
    }
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }
    public Double getNotaCn() {
        return this.notaCn;
    }
    
    public void setNotaCn(Double notaCn) {
        this.notaCn = notaCn;
    }
    public Double getNotaCh() {
        return this.notaCh;
    }
    
    public void setNotaCh(Double notaCh) {
        this.notaCh = notaCh;
    }
    public Double getNotaLc() {
        return this.notaLc;
    }
    
    public void setNotaLc(Double notaLc) {
        this.notaLc = notaLc;
    }
    public Double getNotaMt() {
        return this.notaMt;
    }
    
    public void setNotaMt(Double notaMt) {
        this.notaMt = notaMt;
    }
    public Double getNuNotaRedacao() {
        return this.nuNotaRedacao;
    }
    
    public void setNuNotaRedacao(Double nuNotaRedacao) {
        this.nuNotaRedacao = nuNotaRedacao;
    }




}


