package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1



/**
 * Pesos generated by hbm2java
 */
public class Pesos  implements java.io.Serializable {


     private int codPesos;
     private String noPesos;
     private Double pesoCn;
     private Double pesoCh;
     private Double pesoLc;
     private Double pesoMt;
     private Double pesoRedacao;

    public Pesos() {
    }

	
    public Pesos(int codPesos) {
        this.codPesos = codPesos;
    }
    
    public Pesos(int codPesos, String noPesos, Double pesoCn, Double pesoCh, Double pesoLc, Double pesoMt, Double pesoRedacao) {
       this.codPesos = codPesos;
       this.noPesos = noPesos;
       this.pesoCn = pesoCn;
       this.pesoCh = pesoCh;
       this.pesoLc = pesoLc;
       this.pesoMt = pesoMt;
       this.pesoRedacao = pesoRedacao;
    }
    
     public Pesos(String noPesos, Double pesoCn, Double pesoCh, Double pesoLc, Double pesoMt, Double pesoRedacao) {
       this.noPesos = noPesos;
       this.pesoCn = pesoCn;
       this.pesoCh = pesoCh;
       this.pesoLc = pesoLc;
       this.pesoMt = pesoMt;
       this.pesoRedacao = pesoRedacao;
    }
   
    public int getCodPesos() {
        return this.codPesos;
    }
    
    public void setCodPesos(int codPesos) {
        this.codPesos = codPesos;
    }
    public String getNoPesos() {
        return this.noPesos;
    }
    
    public void setNoPesos(String noPesos) {
        this.noPesos = noPesos;
    }
    public Double getPesoCn() {
        return this.pesoCn;
    }
    
    public void setPesoCn(Double pesoCn) {
        this.pesoCn = pesoCn;
    }
    public Double getPesoCh() {
        return this.pesoCh;
    }
    
    public void setPesoCh(Double pesoCh) {
        this.pesoCh = pesoCh;
    }
    public Double getPesoLc() {
        return this.pesoLc;
    }
    
    public void setPesoLc(Double pesoLc) {
        this.pesoLc = pesoLc;
    }
    public Double getPesoMt() {
        return this.pesoMt;
    }
    
    public void setPesoMt(Double pesoMt) {
        this.pesoMt = pesoMt;
    }
    public Double getPesoRedacao() {
        return this.pesoRedacao;
    }
    
    public void setPesoRedacao(Double pesoRedacao) {
        this.pesoRedacao = pesoRedacao;
    }




}


