package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1



/**
 * Socioeconomico generated by hbm2java
 */
public class Socioeconomico  implements java.io.Serializable {


     private long nuInscricao;
     private Candidato candidato;
     private String q001;
     private String q002;
     private String q003;
     private Byte q004;
     private String q005;
     private String q006;
     private String q007;
     private String q008;
     private String q009;
     private String q010;
     private String q011;
     private String q012;
     private String q013;
     private String q014;
     private String q015;
     private String q016;
     private String q017;
     private String q018;
     private String q019;
     private String q020;
     private String q021;
     private String q022;
     private Boolean q023;
     private Boolean q024;
     private Boolean q025;
     private Boolean q026;
     private Boolean q027;
     private Boolean q028;
     private Boolean q029;
     private String q030;
     private String q031;
     private String q032;
     private String q033;
     private String q034;
     private String q035;
     private String q036;
     private String q037;
     private String q038;
     private String q039;
     private Byte q040;
     private String q041;
     private String q042;
     private String q043;
     private String q044;
     private String q045;
     private String q046;
     private String q047;
     private String q048;
     private String q049;
     private String q050;
     private String q051;
     private String q052;
     private String q053;
     private String q054;
     private String q055;
     private String q056;
     private String q057;
     private String q058;
     private String q059;
     private String q060;
     private String q061;
     private String q062;
     private String q063;
     private String q064;
     private String q065;
     private String q066;
     private String q067;
     private String q068;
     private String q069;
     private String q070;
     private String q071;
     private String q072;
     private String q073;
     private String q074;
     private String q075;
     private String q076;

    public Socioeconomico() {
    }

	
    public Socioeconomico(Candidato candidato) {
        this.candidato = candidato;
    }
    public Socioeconomico(Candidato candidato, String q001, String q002, String q003, Byte q004, String q005, String q006, String q007, String q008, String q009, String q010, String q011, String q012, String q013, String q014, String q015, String q016, String q017, String q018, String q019, String q020, String q021, String q022, Boolean q023, Boolean q024, Boolean q025, Boolean q026, Boolean q027, Boolean q028, Boolean q029, String q030, String q031, String q032, String q033, String q034, String q035, String q036, String q037, String q038, String q039, Byte q040, String q041, String q042, String q043, String q044, String q045, String q046, String q047, String q048, String q049, String q050, String q051, String q052, String q053, String q054, String q055, String q056, String q057, String q058, String q059, String q060, String q061, String q062, String q063, String q064, String q065, String q066, String q067, String q068, String q069, String q070, String q071, String q072, String q073, String q074, String q075, String q076) {
       this.candidato = candidato;
       this.q001 = q001;
       this.q002 = q002;
       this.q003 = q003;
       this.q004 = q004;
       this.q005 = q005;
       this.q006 = q006;
       this.q007 = q007;
       this.q008 = q008;
       this.q009 = q009;
       this.q010 = q010;
       this.q011 = q011;
       this.q012 = q012;
       this.q013 = q013;
       this.q014 = q014;
       this.q015 = q015;
       this.q016 = q016;
       this.q017 = q017;
       this.q018 = q018;
       this.q019 = q019;
       this.q020 = q020;
       this.q021 = q021;
       this.q022 = q022;
       this.q023 = q023;
       this.q024 = q024;
       this.q025 = q025;
       this.q026 = q026;
       this.q027 = q027;
       this.q028 = q028;
       this.q029 = q029;
       this.q030 = q030;
       this.q031 = q031;
       this.q032 = q032;
       this.q033 = q033;
       this.q034 = q034;
       this.q035 = q035;
       this.q036 = q036;
       this.q037 = q037;
       this.q038 = q038;
       this.q039 = q039;
       this.q040 = q040;
       this.q041 = q041;
       this.q042 = q042;
       this.q043 = q043;
       this.q044 = q044;
       this.q045 = q045;
       this.q046 = q046;
       this.q047 = q047;
       this.q048 = q048;
       this.q049 = q049;
       this.q050 = q050;
       this.q051 = q051;
       this.q052 = q052;
       this.q053 = q053;
       this.q054 = q054;
       this.q055 = q055;
       this.q056 = q056;
       this.q057 = q057;
       this.q058 = q058;
       this.q059 = q059;
       this.q060 = q060;
       this.q061 = q061;
       this.q062 = q062;
       this.q063 = q063;
       this.q064 = q064;
       this.q065 = q065;
       this.q066 = q066;
       this.q067 = q067;
       this.q068 = q068;
       this.q069 = q069;
       this.q070 = q070;
       this.q071 = q071;
       this.q072 = q072;
       this.q073 = q073;
       this.q074 = q074;
       this.q075 = q075;
       this.q076 = q076;
    }
   
    public long getNuInscricao() {
        return this.nuInscricao;
    }
    
    public void setNuInscricao(long nuInscricao) {
        this.nuInscricao = nuInscricao;
    }
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }
    public String getQ001() {
        return this.q001;
    }
    
    public void setQ001(String q001) {
        this.q001 = q001;
    }
    public String getQ002() {
        return this.q002;
    }
    
    public void setQ002(String q002) {
        this.q002 = q002;
    }
    public String getQ003() {
        return this.q003;
    }
    
    public void setQ003(String q003) {
        this.q003 = q003;
    }
    public Byte getQ004() {
        return this.q004;
    }
    
    public void setQ004(Byte q004) {
        this.q004 = q004;
    }
    public String getQ005() {
        return this.q005;
    }
    
    public void setQ005(String q005) {
        this.q005 = q005;
    }
    public String getQ006() {
        return this.q006;
    }
    
    public void setQ006(String q006) {
        this.q006 = q006;
    }
    public String getQ007() {
        return this.q007;
    }
    
    public void setQ007(String q007) {
        this.q007 = q007;
    }
    public String getQ008() {
        return this.q008;
    }
    
    public void setQ008(String q008) {
        this.q008 = q008;
    }
    public String getQ009() {
        return this.q009;
    }
    
    public void setQ009(String q009) {
        this.q009 = q009;
    }
    public String getQ010() {
        return this.q010;
    }
    
    public void setQ010(String q010) {
        this.q010 = q010;
    }
    public String getQ011() {
        return this.q011;
    }
    
    public void setQ011(String q011) {
        this.q011 = q011;
    }
    public String getQ012() {
        return this.q012;
    }
    
    public void setQ012(String q012) {
        this.q012 = q012;
    }
    public String getQ013() {
        return this.q013;
    }
    
    public void setQ013(String q013) {
        this.q013 = q013;
    }
    public String getQ014() {
        return this.q014;
    }
    
    public void setQ014(String q014) {
        this.q014 = q014;
    }
    public String getQ015() {
        return this.q015;
    }
    
    public void setQ015(String q015) {
        this.q015 = q015;
    }
    public String getQ016() {
        return this.q016;
    }
    
    public void setQ016(String q016) {
        this.q016 = q016;
    }
    public String getQ017() {
        return this.q017;
    }
    
    public void setQ017(String q017) {
        this.q017 = q017;
    }
    public String getQ018() {
        return this.q018;
    }
    
    public void setQ018(String q018) {
        this.q018 = q018;
    }
    public String getQ019() {
        return this.q019;
    }
    
    public void setQ019(String q019) {
        this.q019 = q019;
    }
    public String getQ020() {
        return this.q020;
    }
    
    public void setQ020(String q020) {
        this.q020 = q020;
    }
    public String getQ021() {
        return this.q021;
    }
    
    public void setQ021(String q021) {
        this.q021 = q021;
    }
    public String getQ022() {
        return this.q022;
    }
    
    public void setQ022(String q022) {
        this.q022 = q022;
    }
    public Boolean getQ023() {
        return this.q023;
    }
    
    public void setQ023(Boolean q023) {
        this.q023 = q023;
    }
    public Boolean getQ024() {
        return this.q024;
    }
    
    public void setQ024(Boolean q024) {
        this.q024 = q024;
    }
    public Boolean getQ025() {
        return this.q025;
    }
    
    public void setQ025(Boolean q025) {
        this.q025 = q025;
    }
    public Boolean getQ026() {
        return this.q026;
    }
    
    public void setQ026(Boolean q026) {
        this.q026 = q026;
    }
    public Boolean getQ027() {
        return this.q027;
    }
    
    public void setQ027(Boolean q027) {
        this.q027 = q027;
    }
    public Boolean getQ028() {
        return this.q028;
    }
    
    public void setQ028(Boolean q028) {
        this.q028 = q028;
    }
    public Boolean getQ029() {
        return this.q029;
    }
    
    public void setQ029(Boolean q029) {
        this.q029 = q029;
    }
    public String getQ030() {
        return this.q030;
    }
    
    public void setQ030(String q030) {
        this.q030 = q030;
    }
    public String getQ031() {
        return this.q031;
    }
    
    public void setQ031(String q031) {
        this.q031 = q031;
    }
    public String getQ032() {
        return this.q032;
    }
    
    public void setQ032(String q032) {
        this.q032 = q032;
    }
    public String getQ033() {
        return this.q033;
    }
    
    public void setQ033(String q033) {
        this.q033 = q033;
    }
    public String getQ034() {
        return this.q034;
    }
    
    public void setQ034(String q034) {
        this.q034 = q034;
    }
    public String getQ035() {
        return this.q035;
    }
    
    public void setQ035(String q035) {
        this.q035 = q035;
    }
    public String getQ036() {
        return this.q036;
    }
    
    public void setQ036(String q036) {
        this.q036 = q036;
    }
    public String getQ037() {
        return this.q037;
    }
    
    public void setQ037(String q037) {
        this.q037 = q037;
    }
    public String getQ038() {
        return this.q038;
    }
    
    public void setQ038(String q038) {
        this.q038 = q038;
    }
    public String getQ039() {
        return this.q039;
    }
    
    public void setQ039(String q039) {
        this.q039 = q039;
    }
    public Byte getQ040() {
        return this.q040;
    }
    
    public void setQ040(Byte q040) {
        this.q040 = q040;
    }
    public String getQ041() {
        return this.q041;
    }
    
    public void setQ041(String q041) {
        this.q041 = q041;
    }
    public String getQ042() {
        return this.q042;
    }
    
    public void setQ042(String q042) {
        this.q042 = q042;
    }
    public String getQ043() {
        return this.q043;
    }
    
    public void setQ043(String q043) {
        this.q043 = q043;
    }
    public String getQ044() {
        return this.q044;
    }
    
    public void setQ044(String q044) {
        this.q044 = q044;
    }
    public String getQ045() {
        return this.q045;
    }
    
    public void setQ045(String q045) {
        this.q045 = q045;
    }
    public String getQ046() {
        return this.q046;
    }
    
    public void setQ046(String q046) {
        this.q046 = q046;
    }
    public String getQ047() {
        return this.q047;
    }
    
    public void setQ047(String q047) {
        this.q047 = q047;
    }
    public String getQ048() {
        return this.q048;
    }
    
    public void setQ048(String q048) {
        this.q048 = q048;
    }
    public String getQ049() {
        return this.q049;
    }
    
    public void setQ049(String q049) {
        this.q049 = q049;
    }
    public String getQ050() {
        return this.q050;
    }
    
    public void setQ050(String q050) {
        this.q050 = q050;
    }
    public String getQ051() {
        return this.q051;
    }
    
    public void setQ051(String q051) {
        this.q051 = q051;
    }
    public String getQ052() {
        return this.q052;
    }
    
    public void setQ052(String q052) {
        this.q052 = q052;
    }
    public String getQ053() {
        return this.q053;
    }
    
    public void setQ053(String q053) {
        this.q053 = q053;
    }
    public String getQ054() {
        return this.q054;
    }
    
    public void setQ054(String q054) {
        this.q054 = q054;
    }
    public String getQ055() {
        return this.q055;
    }
    
    public void setQ055(String q055) {
        this.q055 = q055;
    }
    public String getQ056() {
        return this.q056;
    }
    
    public void setQ056(String q056) {
        this.q056 = q056;
    }
    public String getQ057() {
        return this.q057;
    }
    
    public void setQ057(String q057) {
        this.q057 = q057;
    }
    public String getQ058() {
        return this.q058;
    }
    
    public void setQ058(String q058) {
        this.q058 = q058;
    }
    public String getQ059() {
        return this.q059;
    }
    
    public void setQ059(String q059) {
        this.q059 = q059;
    }
    public String getQ060() {
        return this.q060;
    }
    
    public void setQ060(String q060) {
        this.q060 = q060;
    }
    public String getQ061() {
        return this.q061;
    }
    
    public void setQ061(String q061) {
        this.q061 = q061;
    }
    public String getQ062() {
        return this.q062;
    }
    
    public void setQ062(String q062) {
        this.q062 = q062;
    }
    public String getQ063() {
        return this.q063;
    }
    
    public void setQ063(String q063) {
        this.q063 = q063;
    }
    public String getQ064() {
        return this.q064;
    }
    
    public void setQ064(String q064) {
        this.q064 = q064;
    }
    public String getQ065() {
        return this.q065;
    }
    
    public void setQ065(String q065) {
        this.q065 = q065;
    }
    public String getQ066() {
        return this.q066;
    }
    
    public void setQ066(String q066) {
        this.q066 = q066;
    }
    public String getQ067() {
        return this.q067;
    }
    
    public void setQ067(String q067) {
        this.q067 = q067;
    }
    public String getQ068() {
        return this.q068;
    }
    
    public void setQ068(String q068) {
        this.q068 = q068;
    }
    public String getQ069() {
        return this.q069;
    }
    
    public void setQ069(String q069) {
        this.q069 = q069;
    }
    public String getQ070() {
        return this.q070;
    }
    
    public void setQ070(String q070) {
        this.q070 = q070;
    }
    public String getQ071() {
        return this.q071;
    }
    
    public void setQ071(String q071) {
        this.q071 = q071;
    }
    public String getQ072() {
        return this.q072;
    }
    
    public void setQ072(String q072) {
        this.q072 = q072;
    }
    public String getQ073() {
        return this.q073;
    }
    
    public void setQ073(String q073) {
        this.q073 = q073;
    }
    public String getQ074() {
        return this.q074;
    }
    
    public void setQ074(String q074) {
        this.q074 = q074;
    }
    public String getQ075() {
        return this.q075;
    }
    
    public void setQ075(String q075) {
        this.q075 = q075;
    }
    public String getQ076() {
        return this.q076;
    }
    
    public void setQ076(String q076) {
        this.q076 = q076;
    }




}


