package enem.entity;
// Generated Nov 18, 2017 4:44:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Uf generated by hbm2java
 */
public class Uf  implements java.io.Serializable {


     private byte codUf;
     private String nomeUf;
     private Set candidatosForCodUfNascimento = new HashSet(0);
     private Set candidatosForCodUfResidencia = new HashSet(0);
     private Set escolas = new HashSet(0);
     private Set candidatosForCodUfProva = new HashSet(0);

    public Uf() {
    }

	
    public Uf(byte codUf) {
        this.codUf = codUf;
    }
    public Uf(byte codUf, String nomeUf, Set candidatosForCodUfNascimento, Set candidatosForCodUfResidencia, Set escolas, Set candidatosForCodUfProva) {
       this.codUf = codUf;
       this.nomeUf = nomeUf;
       this.candidatosForCodUfNascimento = candidatosForCodUfNascimento;
       this.candidatosForCodUfResidencia = candidatosForCodUfResidencia;
       this.escolas = escolas;
       this.candidatosForCodUfProva = candidatosForCodUfProva;
    }
   
    public byte getCodUf() {
        return this.codUf;
    }
    
    public void setCodUf(byte codUf) {
        this.codUf = codUf;
    }
    public String getNomeUf() {
        return this.nomeUf;
    }
    
    public void setNomeUf(String nomeUf) {
        this.nomeUf = nomeUf;
    }
    public Set getCandidatosForCodUfNascimento() {
        return this.candidatosForCodUfNascimento;
    }
    
    public void setCandidatosForCodUfNascimento(Set candidatosForCodUfNascimento) {
        this.candidatosForCodUfNascimento = candidatosForCodUfNascimento;
    }
    public Set getCandidatosForCodUfResidencia() {
        return this.candidatosForCodUfResidencia;
    }
    
    public void setCandidatosForCodUfResidencia(Set candidatosForCodUfResidencia) {
        this.candidatosForCodUfResidencia = candidatosForCodUfResidencia;
    }
    public Set getEscolas() {
        return this.escolas;
    }
    
    public void setEscolas(Set escolas) {
        this.escolas = escolas;
    }
    public Set getCandidatosForCodUfProva() {
        return this.candidatosForCodUfProva;
    }
    
    public void setCandidatosForCodUfProva(Set candidatosForCodUfProva) {
        this.candidatosForCodUfProva = candidatosForCodUfProva;
    }




}


